### model
model_name_or_path: /global_data/mllm/models/Qwen2.5-VL-7B-Instruct
image_max_pixels: 3211264
video_max_pixels: 16384
trust_remote_code: true
report_to: []

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z2_config.json # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: raw100w
template: qwen2_vl
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 64


### output
output_dir: /checkpoint_save/
logging_steps: 1
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
flash_attn: fa2
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-7
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
fp16: false  
ddp_timeout: 180000000
